WebSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('', include('main.urls'))
]

cart/urls.py
from django.urls import path
from cart.views import CartView, BuyView, RemoveCart, ConfirmCreateView

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='detail'),
    path('add', BuyView.as_view(), name='add'),
    path('remove', RemoveCart.as_view(), name='remove'),
    path('confirm', ConfirmCreateView.as_view(), name='confirm')

]

cart/models.py
from django.db import models
from main.models import Position
from django.utils.translation import gettext_lazy as _


class ContactInformation(models.Model):
    class Country(models.TextChoices):
        Russia = 'russia', _('Россия')
        Belarus = 'belarus', _('Беларусь')
        Kazakhstan = 'Kazakhstan', _('Казахстан')

    name = models.CharField(max_length=255, verbose_name='Имя')
    surname = models.CharField(max_length=255, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=255, verbose_name='Отчество')
    country = models.CharField(
        _('Страна'),
        max_length=255,
        choices=Country.choices,
        default=Country.Russia
    )
    address = models.CharField(max_length=255, verbose_name='Адрес')
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    email = models.CharField(max_length=100, verbose_name='Email')
    additional = models.TextField(max_length=500, verbose_name='Дополнительная информация')


class Order(models.Model):
    class StatusOrder(models.TextChoices):
        Init = 'init', _('Инициализация')
        In_delivery = 'in_delivery', _('В доставке')
        Done = 'done', _('Выполнен')

    class TypePayment(models.TextChoices):
        Card = 'card', _('Оплата картой')
        Cash = 'cash', _('Наличиными при получении')

    status = models.CharField(
        _('Тип'),
        max_length=100,
        choices=StatusOrder.choices,
        default=StatusOrder.Init
    )

    type_payment = models.CharField(
        _('Тип оплаты'),
        max_length=100,
        choices=TypePayment.choices,
        default=TypePayment.Card
    )

    contact_information = models.ForeignKey(ContactInformation, on_delete=models.CASCADE, blank=True, null=True)


class OrderLine(models.Model):
    """ Позиция в заказе """

    number_of_products = models.IntegerField()
    product_price = models.FloatField()

    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True)

cart/forms.py
from django import forms
from cart.models import ContactInformation


class ContactInformationForm(forms.ModelForm):
    """ Контактная информация """

    CHOICES = [('card', 'Оплата картой'), ('cash', 'Наличными при получении')]
    pay_method = forms.CharField(label='Способ оплаты', widget=forms.RadioSelect(choices=CHOICES))

    class Meta:
        model = ContactInformation
        fields = ['name', 'surname', 'patronymic', 'country', 'address', 'phone', 'email', 'additional']

        widgets = {

            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': 'required',
                    'placeholder': 'Введите имя'
                },
            ),
            'surname': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': 'required',
                    'placeholder': 'Введите фамилию'
                }
            ),
            'patronymic': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': 'required',
                    'placeholder': 'Введите отчество'
                }
            ),
            'country':  forms.Select(
                    attrs={'class': 'form-control my-3 p-4'}
                ),
            'address': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': 'required',
                    'placeholder': 'Введите адрес'
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': 'required',
                    'placeholder': 'Введите номер телефона'
                }
            ),

            'email': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': 'required',
                    'placeholder': 'Введите email'
                }
            ),

            'additional': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Введите дополнительную информацию'
                }
            ),
        }

cart/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, CreateView
from cart.models import OrderLine, Order
from cart.services.cart import get_or_create_cart, add_to_cart, count_total, write_off_postions
from cart.services.notification import send_notification
from cart.forms import ContactInformationForm


class BuyView(View):
    def post(self, request):
        """ Добавление товаров к корзину """
        cart = get_or_create_cart()
        add_to_cart(cart, request)
        return redirect('cart:detail')


class CartView(View):
    def get(self, request):
        """ Просмотр корзины """
        cart = get_or_create_cart()
        order_lines = OrderLine.objects.filter(order=cart).prefetch_related('position')
        return render(request, 'cart/detail.html', {
            'order_lines': order_lines,
            'total': count_total(order_lines)
        })


class RemoveCart(View):
    def get(self, request):
        """ Удаление товаров в корзине """
        cart = get_or_create_cart()
        cart.delete()

        return redirect('cart:detail')


class ConfirmCreateView(CreateView):
    template_name = 'cart/confirmation.html'
    form_class = ContactInformationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = get_or_create_cart()
        order_lines = OrderLine.objects.filter(order=cart).prefetch_related('position')
        context['total'] = count_total(order_lines)
        return context

    def form_valid(self, form):
        contact_information = form.save(commit=False)
        pay_method = form.cleaned_data['pay_method']
        contact_information.save()
        cart = get_or_create_cart()
        Order.objects.filter(id=cart.id).update(
            contact_information=contact_information,
            status='in_delivery',
            type_payment=pay_method
        )
        write_off_postions(cart)

        order_lines = OrderLine.objects.filter(order=cart).prefetch_related('position')
        send_notification(order_lines, count_total(order_lines), contact_information, pay_method)
        return redirect('home')

cart/templates/cart/confirmation.html
{% extends "main/layout/base.html" %}

{% block title %}
    <title>Подтверждение заказа</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="../../static/main/css/YUMMS.css" media="screen">

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section class="u-clearfix u-section-1" id="sec-d0aa">
        <div class="u-clearfix u-sheet ">

            <form  action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                 <div class="col-2"><h6>Итого: {{ total }} ₽</h6></div>
                <button class="btn btn-primary" type="submit">Buy</button>
            </form>
        </div>
    </section>
{% endblock %}

cart/templates/cart/detail.html
{% extends "main/layout/base.html" %}

{% block title %}
    <title>Корзина</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="../../static/main/css/YUMMS.css" media="screen">

     {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section class="u-clearfix u-section-1" id="sec-d0aa">
        <div class="u-clearfix u-sheet u-sheet-1">
        {% if order_lines|length %}
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Position</th>
                    <th scope="col">Size</th>
                    <th scope="col">Number of products</th>
                    <th scope="col">Product price</th>
                </tr>
                </thead>
                <tbody>
                {% for line in order_lines  %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}
                        </th>
                        <td >{{ line.position.product.name}}</td>
                        <td >{{ line.position.size.name}}</td>

                        <td >{{ line.number_of_products}}</td>

                        <td >{{ line.product_price}} ₽</td>

                    </tr>

                {% endfor %}



                </tbody>
            </table>
        <div class="col-2"><h6>Total: {{ total }} ₽</h6></div>
        <a class="btn btn-secondary" href="{% url 'cart:remove' %}">Clear cart</a>
        <a class="btn btn-success" href="{% url 'cart:confirm' %}">Confirm</a>
        {% else %}
        <p>Товаров пока нет</p>
        {% endif %}

        </div>

    </section>
{% endblock %}

cart/templates/cart/notification.html
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Position</th>
        <th scope="col">Size</th>
        <th scope="col">Number of products</th>
        <th scope="col">Product price</th>
    </tr>
    </thead>
    <tbody>
    {% for line in order_lines  %}
        <tr>
            <th scope="row">{{ forloop.counter }}
            </th>
            <td >{{ line.position.product.name}}</td>
            <td >{{ line.position.size.name}}</td>

            <td >{{ line.number_of_products}}</td>

            <td >{{ line.product_price}} ₽</td>

        </tr>

    {% endfor %}



    </tbody>
</table>
<div class="col-2"><h3>Итого: {{ total }} ₽</h3></div>
<br>
<h2>Контактная информация</h2>
<h3>Фамилия: {{ contact_information.surname }}</h3>
<h3>Имя: {{ contact_information.name }}</h3>
<h3>Отчество: {{ contact_information.patronymic }}</h3>
<h3>Страна: {{ contact_information.country }}</h3>
<h3>Адрес: {{ contact_information.address }}</h3>
<h3>Номер телефона: {{ contact_information.phone }}</h3>
<h3>Email: {{ contact_information.email }}</h3>
<h3>Дополнительная информация: {{ contact_information.additional }}</h3>
<h3>Способ оплаты: {{ pay_method }}</h3>