WebSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('', include('main.urls'))
]

cart/urls.py
from django.urls import path
from cart.views import CartView, BuyView, RemoveCart, ConfirmCreateView

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='detail'),
    path('add', BuyView.as_view(), name='add'),
    path('remove', RemoveCart.as_view(), name='remove'),
    path('confirm', ConfirmCreateView.as_view(), name='confirm')

]

main/urls.py
from django.urls import path
from main.views import IndexView, AboutTemplateView, BrandView, ProductDetailView, ConfirmationTemplateView

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('about', AboutTemplateView.as_view(), name='about'),
    path('brand/<slug:brand_slug>/', BrandView.as_view(), name='brand'),
    path('product/<int:id>/<slug:prod_slug>', ProductDetailView.as_view(), name='product'),
    path('confirmation', ConfirmationTemplateView.as_view(), name='confirmation')

]

main/models.py
from django.db import models
from django.urls import reverse


class Brand_s(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(max_length=128, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    description = models.TextField(null=True, blank=True)
    image = models.TextField(null=True)
    image2 = models.TextField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ('brand', kwargs={'brand_slug':self.slug})
        
    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'


class Product_s(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=0)
    image = models.TextField(null=True)
    image2 = models.TextField(null=True)
    category = models.ForeignKey('Brand_s', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ('product', kwargs={ 'id':self.id ,'prod_slug':self.slug})

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Size(models.Model):
    name = models.CharField(max_length=2, verbose_name='Size')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Size'
        verbose_name_plural = 'Size'


class Position(models.Model):
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    product = models.ForeignKey(Product_s, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.quantity} {self.product} {self.size}'

    class Meta:
        verbose_name = 'Position'
        verbose_name_plural = 'Positions'

main/views.py
from django.shortcuts import render, get_object_or_404
from main.models import Brand_s, Product_s, Size, Position
from django.views.generic import View, TemplateView


class IndexView(View):
    """ Главная страница """

    def get(self, request):
        return render(request, 'main/index.html', {
            'brands': Brand_s.objects.all(),
            'items': Product_s.objects.all()
            })


class AboutTemplateView(TemplateView):
    """ О нас """

    template_name = 'main/about.html'


class BrandView(View):
    """ Просмотр товаров бренда """

    def get(self, request, brand_slug):
        br = get_object_or_404(Brand_s, slug=brand_slug)
        items = Product_s.objects.filter(category=br.id)
        return render(request, 'main/product/list.html', {'items': items, 'br': br})


class ProductDetailView(View):
    """ Детальная информация о продукте"""

    def get(self, request, id, prod_slug):
        item = get_object_or_404(Product_s, id=id, slug=prod_slug)
        positions = Position.objects.filter(product=item)
        return render(request, 'main/product/detail.html', {
            'it': item,
            'br_id': item.category,
            'positions': positions

        })


class ConfirmationTemplateView(TemplateView):
    """ Подтверждение заказа """

    template_name = 'main/confirmation.html'

main/templates/main/product/detail.html
{% extends "main/layout/base.html" %}

{% block title %}
    <title>{{it.name}}</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="../../../static/main/css/store.css" media="screen">

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section class="u-clearfix u-section-1" id="sec-b452">
        <div class="u-clearfix u-sheet u-sheet-1">
            <img class="u-image u-image-contain u-image-default u-image-1" src="{{br_id.image2}}" alt="" data-image-width="6168" data-image-height="1477" data-href="{{ br_id.get_absolute_url }}"><!--product--><!--product_options_json--><!--{"source":""}--><!--/product_options_json--><!--product_item-->
            <div class="u-container-style u-expanded-width u-product u-product-1">
                <div class="u-container-layout u-container-layout-1"><!--product_gallery--><!--options_json--><!--{"maxItems":""}--><!--/options_json-->
                    <div class="u-carousel u-gallery u-layout-thumbnails u-lightbox u-no-transition u-product-control u-show-text-none u-thumbnails-position-bottom u-gallery-1" data-interval="5000" data-u-ride="carousel" id="carousel-654c">
                        <div class="u-carousel-inner u-gallery-inner" role="listbox"><!--product_gallery_item-->
                            <div class="active u-active u-carousel-item u-gallery-item u-shape-rectangle">
                                <div class="u-back-slide" data-image-width="1500" data-image-height="1500">
                                    <img class="u-back-image u-expanded" src="{{it.image}}">
                                </div>
                                <div class="u-over-slide u-over-slide-1">
                                    <h3 class="u-gallery-heading">Sample Title</h3>
                                    <p class="u-gallery-text">Sample Text</p>
                                </div>
                            </div><!--/product_gallery_item--><!--product_gallery_item-->
                            <div class="u-carousel-item u-gallery-item u-shape-rectangle">
                                <div class="u-back-slide" data-image-width="1023" data-image-height="1280">
                                    <img class="u-back-image u-expanded" src="{{it.image2}}">
                                </div>
                                <div class="u-over-slide u-over-slide-2">
                                    <h3 class="u-gallery-heading">Sample Title</h3>
                                    <p class="u-gallery-text">Sample Text</p>
                                </div>
                            </div><!--/product_gallery_item-->
                        </div>
                        <a class="u-black u-carousel-control u-carousel-control-prev u-icon-rectangle u-opacity u-opacity-70 u-spacing-15 u-text-body-alt-color u-text-hover-grey-40 u-carousel-control-1" href="#carousel-654c" role="button" data-u-slide="prev">
                <span aria-hidden="true">
                  <svg viewBox="0 0 477.175 477.175"><path d="M145.188,238.575l215.5-215.5c5.3-5.3,5.3-13.8,0-19.1s-13.8-5.3-19.1,0l-225.1,225.1c-5.3,5.3-5.3,13.8,0,19.1l225.1,225
		c2.6,2.6,6.1,4,9.5,4s6.9-1.3,9.5-4c5.3-5.3,5.3-13.8,0-19.1L145.188,238.575z"></path></svg>
                </span>
                            <span class="sr-only">
                  <svg viewBox="0 0 477.175 477.175"><path d="M145.188,238.575l215.5-215.5c5.3-5.3,5.3-13.8,0-19.1s-13.8-5.3-19.1,0l-225.1,225.1c-5.3,5.3-5.3,13.8,0,19.1l225.1,225
		c2.6,2.6,6.1,4,9.5,4s6.9-1.3,9.5-4c5.3-5.3,5.3-13.8,0-19.1L145.188,238.575z"></path></svg>
                </span>
                        </a>
                        <a class="u-black u-carousel-control u-carousel-control-next u-icon-rectangle u-opacity u-opacity-70 u-spacing-15 u-text-body-alt-color u-text-hover-grey-40 u-carousel-control-2" href="#carousel-654c" role="button" data-u-slide="next">
                <span aria-hidden="true">
                  <svg viewBox="0 0 477.175 477.175"><path d="M360.731,229.075l-225.1-225.1c-5.3-5.3-13.8-5.3-19.1,0s-5.3,13.8,0,19.1l215.5,215.5l-215.5,215.5
		c-5.3,5.3-5.3,13.8,0,19.1c2.6,2.6,6.1,4,9.5,4c3.4,0,6.9-1.3,9.5-4l225.1-225.1C365.931,242.875,365.931,234.275,360.731,229.075z"></path></svg>
                </span>
                            <span class="sr-only">
                  <svg viewBox="0 0 477.175 477.175"><path d="M360.731,229.075l-225.1-225.1c-5.3-5.3-13.8-5.3-19.1,0s-5.3,13.8,0,19.1l215.5,215.5l-215.5,215.5
		c-5.3,5.3-5.3,13.8,0,19.1c2.6,2.6,6.1,4,9.5,4c3.4,0,6.9-1.3,9.5-4l225.1-225.1C365.931,242.875,365.931,234.275,360.731,229.075z"></path></svg>
                </span>
                        </a>
                        <ol class="u-carousel-thumbnails u-spacing-25 u-carousel-thumbnails-1"><!--product_gallery_thumbnail-->
                            <li class="u-active u-carousel-thumbnail u-carousel-thumbnail-1" data-u-target="#carousel-654c" data-u-slide-to="0">
                                <img class="u-carousel-thumbnail-image u-image" src="{{it.image}}">
                            </li><!--/product_gallery_thumbnail--><!--product_gallery_thumbnail-->
                            <li class="u-carousel-thumbnail u-carousel-thumbnail-2" data-u-target="#carousel-654c" data-u-slide-to="1">
                                <img class="u-carousel-thumbnail-image u-image" src="{{it.image2}}">
                            </li><!--/product_gallery_thumbnail-->
                        </ol>
                    </div><!--/product_gallery-->
                    <h4 class="u-text u-text-default u-text-1">{{it.name}}</h4>
                    <h6 class="u-text u-text-default u-text-2"> {{it.price}}&nbsp;₽ </h6>
                    <form action="{% url 'cart:add'%}" method="POST">
                        <div class="u-product-control u-product-variations u-product-variations-1"><!--product_variation-->
                            <div class="u-product-variant">
                                <label for="product-variant-select-1" class="u-label"><!--product_variation_label_content-->Size<!--/product_variation_label_content--></label>
                                <div class="u-form-select-wrapper">

                                    <select id="product-variant-select-1" class="u-border-1 u-border-grey-30 u-grey-10 u-input u-input-rectangle" name="size"><!--product_variation_option-->
                                        {% for position in positions %}
                                            {% if position.quantity > 0 %}
                                                <option selected value= "{{ position.size.id }}">
                                                    {{ position.size.name }}
                                                </option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                    <svg class="u-caret u-caret-svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="fill:currentColor;" xml:space="preserve"><polygon class="st0" points="8,12 2,4 14,4 "></polygon></svg>
                                </div>
                            </div>
                        </div>

                        <div class="u-product-control u-product-variations u-product-variations-1">

                            {% csrf_token %}
                            <input type="hidden" value = "{{it.id}}" name="product_id">

                            <button type="submit" class="btn btn-secondary">Add to cart</button>

                        </div>
                    </form>
                    <p class="u-text u-text-default u-text-3">{{it.description|linebreaks}}
                    </p>
                </div>
            </div><!--/product_item--><!--/product-->
        </div>
    </section>
{% endblock %}

main/templates/main/product/list.html
{% extends "main/layout/base.html" %}

{% block title %}
    <title>{{ br.name }}</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="../../../static/main/css/YUMMS.css" media="screen">
{% endblock %}

{% block content %}
    <section class="u-align-center u-clearfix u-section-1" id="sec-5aec">
        <div class="u-clearfix u-sheet u-sheet-1">
            <img class="u-image u-image-contain u-image-default u-image-1" src="{{ br.image2 }}" alt="" data-image-width="6168" data-image-height="1477"><!--products--><!--products_options_json--><!--{"type":"Recent","source":"","tags":"","count":""}--><!--/products_options_json-->
            <div class="u-expanded-width u-products u-products-1">
                <div class="u-repeater u-repeater-1"><!--product_item-->
                    {% for tab in items %}
                        <div class="u-align-center u-container-style u-products-item u-repeater-item" data-href="{{ tab.get_absolute_url }}"  rel="nofollow">
                            <div class="u-container-layout u-similar-container u-valign-top u-container-layout-3"><!--product_image-->
                                <img class="u-expanded-width u-hover-feature u-image u-product-control u-image-3" src="{{ tab.image }}" data-image-width="458" data-image-height="458"><!--/product_image-->
                                <div class="u-align-center u-container-style u-group u-white u-group-2">
                                    <div class="u-container-layout u-container-layout-4">
                                        <h4 class="u-text u-text-3">{{ tab.name }}</h4>
                                        <p class="u-text u-text-4"> {{ tab.price }}&nbsp;₽</p>
                                    </div>
                                </div>
                            </div>
                        </div><!--/product_item--><!--product_item-->
                    {% endfor %}

                </div>
            </div><!--/products--><!--products--><!--products_options_json--><!--{"type":"Recent","source":"","tags":"","count":""}--><!--/products_options_json-->
        </div>


    </section>
{% endblock %}``