WebSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('', include('main.urls'))
]

cart/urls.py
from django.urls import path
from cart.views import CartView, BuyView, RemoveCart, ConfirmCreateView

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='detail'),
    path('add', BuyView.as_view(), name='add'),
    path('remove', RemoveCart.as_view(), name='remove'),
    path('confirm', ConfirmCreateView.as_view(), name='confirm')

]

main/urls.py
from django.urls import path
from main.views import IndexView, AboutTemplateView, BrandView, ProductDetailView, ConfirmationTemplateView

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('about', AboutTemplateView.as_view(), name='about'),
    path('brand/<slug:brand_slug>/', BrandView.as_view(), name='brand'),
    path('product/<int:id>/<slug:prod_slug>', ProductDetailView.as_view(), name='product'),
    path('confirmation', ConfirmationTemplateView.as_view(), name='confirmation')

]

main/models.py
from django.db import models
from django.urls import reverse


class Brand_s(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(max_length=128, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    description = models.TextField(null=True, blank=True)
    image = models.TextField(null=True)
    image2 = models.TextField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ('brand', kwargs={'brand_slug':self.slug})
        
    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'


class Product_s(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=0)
    image = models.TextField(null=True)
    image2 = models.TextField(null=True)
    category = models.ForeignKey('Brand_s', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ('product', kwargs={ 'id':self.id ,'prod_slug':self.slug})

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Size(models.Model):
    name = models.CharField(max_length=2, verbose_name='Size')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Size'
        verbose_name_plural = 'Size'


class Position(models.Model):
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    product = models.ForeignKey(Product_s, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.quantity} {self.product} {self.size}'

    class Meta:
        verbose_name = 'Position'
        verbose_name_plural = 'Positions'

main/views.py
from django.shortcuts import render, get_object_or_404
from main.models import Brand_s, Product_s, Size, Position
from django.views.generic import View, TemplateView


class IndexView(View):
    """ Главная страница """

    def get(self, request):
        return render(request, 'main/index.html', {
            'brands': Brand_s.objects.all(),
            'items': Product_s.objects.all()
            })


class AboutTemplateView(TemplateView):
    """ О нас """

    template_name = 'main/about.html'


class BrandView(View):
    """ Просмотр товаров бренда """

    def get(self, request, brand_slug):
        br = get_object_or_404(Brand_s, slug=brand_slug)
        items = Product_s.objects.filter(category=br.id)
        return render(request, 'main/product/list.html', {'items': items, 'br': br})


class ProductDetailView(View):
    """ Детальная информация о продукте"""

    def get(self, request, id, prod_slug):
        item = get_object_or_404(Product_s, id=id, slug=prod_slug)
        positions = Position.objects.filter(product=item)
        return render(request, 'main/product/detail.html', {
            'it': item,
            'br_id': item.category,
            'positions': positions

        })


class ConfirmationTemplateView(TemplateView):
    """ Подтверждение заказа """

    template_name = 'main/confirmation.html'

main/templates/main/layout/base.html
<!DOCTYPE html>
<html style="font-size: 16px;" lang="ru"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
      {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="../../../static/main/css/nicepage.css" media="screen">
    {% block style %}
    {% endblock %}

    <script class="u-script" type="text/javascript" src="../../../static/main/js/jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="../../../static/main/js/nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 4.20.1, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">


    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="about">
    <meta property="og:type" content="website">
</head>
<body class="u-body u-xl-mode" data-lang="ru"><header class="u-clearfix u-header u-valign-middle u-header" id="sec-860b"><span class="u-file-icon u-hover-feature u-icon u-text-black u-icon-1" data-href="{% url 'cart:detail' %}"  rel="nofollow"><img src="../../../static/main/img/2696198-f9460fee.png" alt=""></span><div class="u-container-style u-group u-white u-group-1" rel="nofollow" data-href="/" >        <div class="u-container-layout u-container-layout-1">
    <p class="u-hover-feature u-text u-text-default u-text-1">LameLand</p>
    <img class="u-image u-image-default u-image-1" src="../../../static/main/img/logo.png" alt="" data-image-width="551" data-image-height="500">
</div>
</div><div class="u-container-style u-group u-white u-group-2" data-href="{%url 'about'%}">
    <div class="u-container-layout">
        <nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">
            <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700;">
                <a class="u-button-style u-custom-border u-custom-border-color u-custom-borders u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
                    <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
                    <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
                    </g></svg>
                </a>
            </div>
            <div class="u-custom-menu u-nav-container">
                <ul class="u-nav u-spacing-20 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-black u-text-body-color u-text-hover-grey-40" href="{% url 'about' %}" style="padding: 10px;">О нас</a>
                </li></ul>
            </div>
            <div class="u-custom-menu u-nav-container-collapse">
                <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                    <div class="u-inner-container-layout u-sidenav-overflow">
                        <div class="u-menu-close"></div>
                        <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'about' %}">О нас</a>
                        </li></ul>
                    </div>
                </div>
                <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
            </div>
        </nav>
    </div>
</div></header>

{% block content %}
{% endblock %}




</body></html>